export const selectors = {

    username: "#username",
    password: "#password",
    loginBtn: "Login",
    applauncherIcon: ".slds-icon-waffle",
    homeLabel: "//h1//span[text()='Home']",
    viewAllBtn: `//button[text()="View All"]`,
    appItemSearchField: "one-app-launcher-modal input.slds-input",
    appOrItem: (appName: string) => `//mark[text()='${appName}']`,
    saveBtn: `//button[text()='Save']`,
    newBtn: `//div[@title="New"]`,
    deleteBtn: "span:text-is('Delete')",
    deletePopUp: `//button/span[text()='Delete']`,
    noItemToDisplay: "//span[text()='No items to display.']",
    editBtn: `//button[text()='Edit']`,
    deleteActionBtn: `button[title='Delete']`,

    // AccountPage Selectors
    accounts: {
        tabName: (tabName: string) => `//a[@title='${tabName}']`,
        website: `//input[@name='Website']`,
        newBtn: `//div[@title='New']`,
        accountNameInput: `//input[@name='Name']`,
        accountNameInput2: `//label[text()='Account Name']//following::input[1]`,
        searchInput: `//input[@placeholder='Search this list...']`,
        phone: `//input[@name='Phone']`,
        industryDD: `//button[@aria-label='Industry']/span`,
        industryDDBtn: `//label[text()='Industry']//following::button[1]`,
        industryValue: (industry: string) => `//span[@title='${industry}']`,
        ratingDDBtn: "//label[text()='Rating']//following::button[1]",
        dropdownValueSelector: (data: string) => `//span[text()='${data}']`,
        accountNumberInput: `//label[text()='Account Number']//following::input[1]`,
        accountTypeDDBtn: "//label[text()='Type']//following::button[1]",
        Searchthis: `Search this list...`,
        ownershipDDBtn: `//label[text()='Ownership']//following::button[1]`,
        billingStreetInput: `//label[text()='Billing Street']//following::textarea[1]`,
        billingCityInput: "//label[text()='Billing City']//following::input[1]",
        postalCodeInput: `//label[text()='Billing Zip/Postal Code']//following::input[1]`,
        billingStateInput: `//label[text()='Billing State/Province']//following::input[1]`,
        billingCountryInput: "//label[text()='Billing Country']//following::input[1]",
        saveBtn: `//button[@name='SaveEdit']`,
        moreActionsBtn: `(//button[contains(@class,'slds-button slds-button_icon-border')])[1]`,
        editLink: `//a[@title='Edit']`,
        deleteLink: `//a[@title='Delete']`,
        deleteBtn: `//button[@title='Delete']`,
        toastMessage: `//span[@class='toastMessage slds-text-heading--small forceActionsText']`,
        verificationText: `//slot//lightning-formatted-text[@slot='primaryField']`,
        closeTab: `a[title$ = 'Account'] + * + button`,
    },

    // CasePage Selectors
    cases: {
        newBtnAlt: `//button[text()='New']`,
        newBtn: `//div[@title='New']`,
        newBtn2: `div:text-is('New')`,
        contactNameInput: `//label[text()='Contact Name']/following::input[1]`,
        newContactBtn: `//span[@title="New Contact"]`,
        searchContact:`//input[@placeholder="Search Contacts..."]`,
        newContactBtnAlt: `//span[@title='New Contact']`,
        newContactBtn2: `//button[text()='New Contact']`,
        salutationDD: `//label[text()='Salutation']/following::button[1]`,
        salutationValue: (value: string) => `//span[@title='${value}']`,
        firstNameInput: `//label[text()='First Name']/following::input[1]`,
        lastNameInput: `//label[text()='Last Name']/following::input[1]`,
        saveContactBtn: `(//button[@name='SaveEdit'])[2]`,
        saveContactBtn2: `//button[text()='Save']`,
        caseOriginDD: `//label[text()='Case Origin']/following::button[1]`,
        originDD: `//label[text()='Case Origin']//following::button[1]`,
        statusDD: `//label[text()='Status']/following::button[1]`,
        statusValue: (value: string) => `//label[text()='Status']/following::button[1]/following::span[@title='${value}']`,
        slaViolationDD: `//label[text()='SLA Violation']/following::button[1]`,
        slaViolationValue: (value: string) => `//label[text()='SLA Violation']/following::button[1]/following::span[text()='${value}']`,
        subjectInput: `//label[text()='Subject']/following::input[1]`,
        descriptionInput: `//label[text()='Description']/following::textarea[1]`,
        saveBtn: `(//button[@name='SaveEdit'])[1]`,
        editBtn: `//button[text()='Edit']`,
        deleteBtn: `//button[text()='Delete']`,
        deleteConfirm: `//span[text()='Delete']`,
        toastMessage: `//span[@class='toastMessage slds-text-heading--small forceActionsText']`,
        verificationText: (text: string) => `(//span[contains(text(),'${text}')])[1]`,
        caseRecordLink: (caseNumber: string) => `//a[contains(., '${caseNumber}')]`,
        searchInput: `//input[@placeholder='Search this list...']`,
        deleteActionBtn: `button[title='Delete']`,
        dropdownValueSelector: (value: string) => `//div[contains(@class,"slds-dropdown")]//span[@title="${value}"]`,
        closeTab: `a[title$ = 'Case'] + * + button`,
    },

    // ContactPage Selectors
    contacts: {
        newBtn: `//div[text()='New']`,
        searchInput: `(//input[@type='search'])[2]`,
        dropdownIcon: `//span[@class='slds-icon_container slds-icon-utility-down']/span`,
        deleteLink: `//a[@title='Delete']`,
        deleteBtn: `//button[@title='Delete']`,
        deleteActionBtn: `button[title='Delete']`,
        phoneInput: `input[name='Phone']`,
        homePhoneInput: `input[name='HomePhone']`,
        firstNameInput: `input[name='firstName']`,
        lastNameInput: `input[name='lastName']`,
        accountNameField: `label:text-is('Account Name') + * input`,
        newAccountTag: `span[title='New Account']`,
        newAccountHeader: `h1:text-is('New Account')`,
        salutationDD: `//label[text()='Salutation']//following::button[1]`,
        emailInput: `//label[text()='Email']//following::input[1]`,
        contactRecordLink: (contactName: string) => `//a[contains(., '${contactName}')]`,
        verificationText: `//slot//lightning-formatted-text[@slot='primaryField']`,
        editBtn: `//button[text()='Edit']`,
        closeTab: `a[title$ = 'Contact'] + * + button`,
        saveBtn: `//button[text()='Save']`,
        dropdownValueSelector: (data: string) => `//span[text()='${data}']`,
    },

    // CreateContactPage Selectors
    createContact: {
        salutationDD: `(//div[contains(@class,'slds-combobox__form-element slds-input-has-icon')]//button)[2]`,
        salutationValue: `//span[text()='Mr.']`,
        firstNameInput: `//label[text()='First Name']/following::input`,
        lastNameInput: `//label[text()='Last Name']/following::input`,
        saveBtn: `(//button[text()='Save'])[2]`,
    },

    // CreateLegalEntityPage Selectors
    createLegalEntity: {
        salutationDD: `(//div[contains(@class,'slds-combobox__form-element slds-input-has-icon')]//button)[2]`,
        salutationValue: `//span[text()='Mr.']`,
        legalEntityNameInput: `//label[text()='Legal Entity Name']/following::input`,
        descriptionInput: `//label[text()='Last Name']/following::input`,
        nameInput: `//label[text()='Name']//following::input[1]`,
        statusDD: `//label[text()='Status']//following::button[1]`,
        saveBtn: `(//button[text()='Save'])[2]`,
    },

    // CreateNewOpportunitiesPage Selectors
    createOpportunity: {
        opportunityNameInput: `//label[text()='Opportunity Name']/following::input[1]`,
        closeDateInput: `//label[text()='Close Date']/following::input[1]`,
        todayBtn: `//button[text()='Today']`,
        stageDD: `//label[text()='Stage']/following::button[1]`,
        stageValue: `//div[@aria-label='Stage']//span[text()='Needs Analysis']`,
        saveBtn: `//button[@name='SaveEdit']`,
    },

    // DeleteContactPage Selectors
    deleteContact: {
        moreActionsBtn: `(//button[contains(@class,'slds-button slds-button_icon-border')])[1]`,
        deleteLink: `//a[@title='Delete']//div`,
        deleteConfirm: `//span[text()='Delete']`,
    },

    // EditContactPage Selectors
    editContact: {
        moreActionsBtn: `(//button[contains(@class,'slds-button slds-button_icon-border')])[1]`,
        editLink: `//a[@title='Edit']//div`,
        phoneInput: `//input[@name='Phone']`,
        saveBtn: `(//button[text()='Save'])[2]`,
    },

    // EditLegalEntityPage Selectors
    editLegalEntity: {
        showActionsBtn: `//button[.//span[text()='Show Actions']]`,
        editLink: `//a[@title='Edit']//div`,
        companyNameInput: `(//label[text()='Company Name']/following::input)`,
        descriptionInput: `(//label[text()='Description']/following::textarea)`,
        statusDD: `//label[text()='Status']/following::button`,
        statusValue: `//span[@title='Active']`,
        nameInput: `//label[text()='Name']//following::input[1]`,
        saveBtn: `(//button[text()='Save'])[2]`,
    },

    // EditOpportunityPage Selectors
    editOpportunity: {
        closeDateInput: `//label[text()='Close Date']/following::input[1]`,
        todayDate: `//td[@class='slds-is-today slds-is-selected']/following-sibling::td/span`,
        stageDD: `//label[text()='Stage']/following::button[1]`,
        stageValue: `//div[@aria-label='Stage']//span[text()='Perception Analysis']`,
        descriptionInput: `//label[text()='Description']/following::textarea[1]`,
        saveBtn: `//button[@name='SaveEdit']`,
    },

    // HomePage Selectors
    home: {
        homeLabel: `//span[text()='Home']`,
        appLauncherIcon: `//div[@class='slds-icon-waffle']`,
        viewAllBtn: `//button[text()='View All']`,
        appSearchInput: `//input[@placeholder='Search apps or items...']`,
        casesApp: `(//p[@class='slds-truncate']/mark[text()='Cases'])[1]`,
        legalEntitiesApp: `(//p[@class='slds-truncate']/mark[text()='Legal Entities'])`,
        leadsApp: `//a[@title='Leads']`,
        selectApp: (appName: string) => `//mark[text()='${appName}']`,
        individualsApp: `(//mark[text()='Individuals'])`,
        workTypeApp: `//mark[text()='Work Type']`,
        salesApp: `(//p[@class='slds-truncate']/mark[text()='Sales'])[3]`,
        opportunitiesApp: `//span[text()='Opportunities']`,
        tasksApp: `//span[text()='Tasks']`,
        contactsApp: `//span[text()='Contacts']`,
    },

    // IndividualsPage Selectors
    individuals: {
        details:`//span[text()='Details']`,
        newBtn: `//div[text()='New']`,
        salutationLink: `//span[text()='Salutation']/following::a[1]`,
        salutationValue: `//a[@title='Mr.']`,
        salutationDD: `//span[text()='Salutation']/following::a[1]`,
        firstNameInput: `//span[text()='First Name']/following::input[1]`,
        firstNameInput2: `//label[text()='First Name']/following::input[1]`,
        lastNameInput: `//span[text()='Last Name']/following::input[1]`,
        lastNameInput2: `//label[text()='Last Name']/following::input[1]`,
        saveBtn: `//span[text()='Save']`,
        toastMessage: `//span[@class='toastMessage slds-text-heading--small forceActionsText']`,
        searchInput: `//input[@placeholder='Search this list...']`,
        moreActionsBtn: `(//button[contains(@class,'slds-button slds-button_icon-border')])[2]`,
        deleteLink: `//a[@title='Delete']`,
        deleteConfirm: `//span[text()='Delete']`,
        deleteBtn: `//span[text()='Delete']`,
        toastMsg: `//span[contains(@class,'toastMessage')]`,
        editLink: `//a[@title='Edit']`,
        editBtn: `//button[text()='Edit']`,
        individualRecordLink: (name: string) => `//a[contains(., '${name}')]`,
        verificationText: `//div[.//button[@title="Edit Name"]]/span[contains(@class,"test-id__field-value")]/span`,
        deleteActionBtn: `button[title='Delete']`,
        dropdownValueSelector: (data: string) => `//a[@title='${data}']`,
        closeTab: `a[title$ = 'Individual'] + * + button`,
    },

    // LeadsPage Selectors
    leads: {
        newBtn: `//div[@title='New']`,
        moreActionsBtn: `(//button[contains(@class,'slds-button slds-button_icon-border')])[1]`,
        editLink: `//a[@title='Edit']`,
        firstNameInput: `//input[@name='firstName']`,
        firstName: "//label[text()='First Name']//following::input[1]",
        saveBtn: `//button[@name='SaveEdit']`,
        toastMessage: `//span[@class='toastMessage slds-text-heading--small forceActionsText']`,
        salutationDD: `//label[text()='Salutation']//following::button[1]`,
        salutationValue: `//span[text()='Mr.']`,
        firstNameLabel: `//label[text()='First Name']/following::input`,
        lastNameLabel: `//label[text()='Last Name']/following::input`,
        companyLabel: `//label[text()='Company']/following::input`,
        salutation: "button[name='salutation']",
        saluationValue: (value: string) => "span:text-is('" + value + "')",
        lastName: "//label[text()='Last Name']//following::input[1]",
        company: "//label[text()='Company']//following::input[1]",
        verificationText: "slot[name='primaryField'] lightning-formatted-name",
        searchLeadInput: "div[class^='slds-form-element__control'] input",
        userId: (userName: string) => "//a[@title='" + userName + "']",
        expandBtn: "[class^='menu-button-item'] button",
        searchInput: `//input[@placeholder='Search this list...']`,
        leadRecordLink: (leadName: string) => `//a[contains(., '${leadName}')]`,
        editBtn: `//button[text()='Edit']`,
        deleteBtn: `//button[text()='Delete']`,
    },

    // LegalEntity Selectors
    legalEntity: {
        newBtn: `//div[text()='New']`,
        searchInput: `(//input[@type='search'])[2]`,
        nameInput: `//label[text()='Name']//following::input[1]`,
        statusDD: `//label[text()='Status']//following::button[1]`,
        verificationText: `//slot//lightning-formatted-text[@slot='primaryField']`,
        legalEntityRecordLink: (name: string) => `//a[contains(., '${name}')]`,
        editBtn: `//button[text()='Edit']`,
        deleteActionBtn: `button[title='Delete']`,
        deleteBtn: `//button[@title='Delete']`,
        dropdownValueSelector: (data: string) => `//span[text()='${data}']`,
        closeTab: `a[title$ = 'Legal Entity'] + * + button`,
    },

    // OpportunityPage Selectors
    opportunities: {
        newBtn: `//div[@title='New']`,
        editAction: `//span[@data-cell-type='lstOutputLookup']/following::span[@data-cell-type='lstListViewRowLevelAction']`,
        editLink: `//a[@title='Edit']`,
        editBtn: `//button[text()='Edit']`,
        deleteLink: `//a[@title='Delete']`,
        deleteBtn: `//button[@title='Delete']`,
        opportunityNameInput: `//label[text()='Opportunity Name']//following::input[1]`,
        stageDD: `//label[text()='Stage']//following::button[1]`,
        closeeDateInput: `//label[text()='Close Date']//following::input[1]`,
        amountInput: `//label[text()='Amount']//following::input[1]`,
        verificationText: `//slot//lightning-formatted-text[@slot='primaryField']`,
        searchInput: `//input[@placeholder='Search this list...']`,
        opportunityRecordLink: (oppName: string) => `//a[contains(., '${oppName}')]`,
        deleteActionBtn: `button[title='Delete']`,
        dropdownValueSelector: (data: string) => `//span[text()='${data}']`,
        closeTab: `a[title$ = 'Opportunity'] + * + button`,
        accountNameField: `//label[text()='Account Name']//following::input[1]`,
        saveBtn: `//button[@name='SaveEdit']`,
    },

    // TasksPage Selectors
    tasks: {
        newTaskBtn: `//div[text()='New Task']`,
        contactSearchInput: `//input[@placeholder='Search Contacts...']`,
        primaryLabel: `//div[contains(@class,'primaryLabel')]//span`,
        commentsTextarea: `(//span[text()='Comments'])[2]/following::textarea`,
        saveBtn: `(//span[text()='Save'])[2]`,
        deleteBtn: `//span[normalize-space()='Delete']`,
        deleteConfirm: `//span[normalize-space()='Delete']`,
        errorMsg: `//span[@class='genericError uiOutputText']`,
        subjectInput: `//label[text()='Subject']/following::input[1]`,
        statusDD: `//a[@role='combobox']`,
        statusValue: (status: string) => `//a[@title='${status}']`,
        toastMessage: `//span[contains(@class,'toastMessage slds-text-heading--small forceActionsText')]`,
        listViewBtn: `//button[@title='Select a List View: Tasks']`,
        recentlyViewedOption: `//a[@role='option']//span[text()='Recently Viewed']`,
        listDisplayBtn: `//button[@title='Select list display']`,
        tableOption: `//span[text()='Table']`,
        dropdownIcon: `//span[@class='slds-icon_container slds-icon-utility-down']/span`,
        editOption: `//div[text()='Edit']`,
        dueDateInput: `//label[text()='Due Date']/following::input[1]`,
        priorityDD: `(//a[@role='combobox'])[2]`,
        priorityValue: (priority: string) => `//a[text()='${priority}']`,
        deleteLink: `//a[@data-target-selection-name='sfdc:StandardButton.Task.Delete']`,
        descriptionInput: `//label[text()='Description']/following::textarea[1]`,
        verificationText: `//slot//lightning-formatted-text[@slot='primaryField']`,
        searchInput: `//input[@placeholder='Search this list...']`,
        taskRecordLink: (taskName: string) => `//a[contains(., '${taskName}')]`,
        editBtn: `//button[text()='Edit']`,
        deleteActionBtn: `button[title='Delete']`,
        dropdownValueSelector: (data: string) => `//span[text()='${data}']`,
        closeTab: `a[title$ = 'Task'] + * + button`,
    },

    // VerifyEditContactPage Selectors
    verifyEditContact: {
        toastMessage: `//span[@class='toastMessage slds-text-heading--small forceActionsText']`,
    },

    // VerifyEditLegalEntityPage Selectors
    verifyEditLegalEntity: {
        toastMessage: `//span[contains(@class,'toastMessage slds-text-heading--small forceActionsText')]`,
        legalEntityLink: (leName: string) => `//a[@title='${leName}']`,
        companyName: `//span[text()='Company Name']//following::span`,
        description: `//span[text()='Description']//following::span`,
    },

    // VerifyNewContact Selectors
    verifyNewContact: {
        toastMessage: `//span[contains(@class,'toastMessage slds-text-heading--small forceActionsText')]`,
    },

    // VerifyOpportunity Selectors
    verifyOpportunity: {
        actionText: `//span[@data-aura-class='forceActionsText']`,
        stageName: `//span[@data-cell-type='sfaOutputStageName']//span`,
    },

    // WorkTypeGroupPage Selectors
    workTypeGroup: {
        workTypeGroupLink: `//span[contains(text(),'Work Type Groups')]/following::a[1]`,
        newWorkTypeGroupBtn: `//span[text()='New Work Type Group']`,
        nameInput: `//input[@name='Name']`,
        descriptionInput: `//span[text()='Description']/following::textarea[1]`,
        groupTypeLabel: `//label[text()='Group Type']`,
        capacityOption: `//span[text()='Capacity']`,
        saveBtn: `//button[@name='SaveEdit']`,
        toastMessage: `//span[@class='toastMessage slds-text-heading--small forceActionsText']`,
        searchInput: `//input[@placeholder='Search this list...']`,
        moreActionsBtn: `(//button[contains(@class,'slds-button slds-button_icon-border')])[1]`,
        editLink: `//a[@title='Edit']`,
        deleteLink: `//a[@title='Delete']`,
        deleteBtn: `//button[@title='Delete']`,
    },

    // WorkTypes Selectors
    workTypes: {
        nameInput: `//label[text()='Name']//following::input[1]`,
        descriptionInput: `//label[text()='Description']//following::textarea[1]`,
        verificationText: `//slot//lightning-formatted-text[@slot='primaryField']`,
        searchInput: `//input[@placeholder='Search this list...']`,
        workTypeRecordLink: (name: string) => `//a[contains(., '${name}')]`,
        editBtn: `//button[text()='Edit']`,
        deleteActionBtn: `button[title='Delete']`,
        closeTab: `a[title$ = 'Work Type'] + * + button`,
    },
};
